name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    uses: ./.github/workflows/python-setup.yml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run flake8
        run: inv lint.flake8

      - name: Run black
        run: inv lint.black

      - name: Run isort
        run: inv lint.isort
  build:
    name: Build
    runs-on: ubuntu-latest
    uses: ./.github/workflows/python-setup.yml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Docker Containers
        run: inv docker.build --daemon --up

      - name: List Running Containers
        run: docker ps -a

      - name: Run Migrations
        run: inv django.migrate

      - name: Save Docker Image
        uses: actions/cache@v3
        with:
          path: ./docker_images/
          key: ${{ runner.os }}-docker-image-${{ github.sha }}
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    uses: ./.github/workflows/python-setup.yml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load Docker Image
        uses: actions/cache@v3
        with:
          path: ./docker_images/
          key: ${{ runner.os }}-docker-image-${{ github.sha }}

      - name: Run Pytest
        run: inv test.pytest

