name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black
        run: invoke lint.black

      - name: Run isort
        run: invoke lint.isort

      - name: Run flake8
        run: invoke lint.flake8

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    env:
      DATABASE_URL: postgres://postgres:D3vP0stgr3s!@postgres:5432/elodrinks_db
      DJANGO_SETTINGS_MODULE: elo_drinks.settings
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Docker Containers
        run: docker compose -f docker-compose.yml up --build -d

      - name: Wait for PostgreSQL
        run: |
          until docker exec postgres pg_isready -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: List Running Containers
        run: docker ps -a

      - name: Run Migrations
        run: invoke django.migrate

      - name: Run Pytest
        run: django invoke test.pytest

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker compose -f docker-compose.yml up --build -d django

      - name: Run Migrations
        run: docker compose exec -T django invoke django.migrate

      - name: Collect Static Files
        run: docker compose exec -T django python manage.py collectstatic --noinput
