name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/python-setup

      - name: Run flake8
        run: inv lint.flake8

      - name: Run black
        run: inv lint.black

      - name: Run isort
        run: inv lint.isort
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/python-setup

      - name: Start Docker Containers
        run: inv docker.build --daemon --up

      - name: List Running Containers
        run: docker ps -a

      - name: Run Migrations
        run: inv django.migrate

      - name: Save Docker Image as Tarball
        run: docker save my-docker-image:latest -o ./docker_images/my_docker_image.tar

      - name: Cache Docker Image Tarball
        uses: actions/cache@v3
        with:
          path: ./docker_images/my_docker_image.tar
          key: ${{ runner.os }}-docker-image-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-image-
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/python-setup

      - name: Load Docker Image from Cache
        run: |
          if [ -f ./docker_images/my_docker_image.tar ]; then
            docker load -i ./docker_images/my_docker_image.tar
          fi

      - name: Run Pytest
        run: inv test.pytest

