name: Python Setup

on:
  workflow_call:

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cache-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-cache-

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt